name: Release with PDF

on:
  push:
    tags:
      - "v*" # Example: v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: main.pdf
